version: "3.3"

services:
    app-1: &app
        image: vadimmakerov/valuator-app
        build:
            context: ./Valuator
        container_name: dotnet_app-1
        volumes:
            - ./Valuator/wwwroot:/app/wwwroot
        env_file:
            - ./Valuator/.env
            
#    app-2: *app
#        container_name: dotnet_app-2
        
    nginx:
        image: nginx:latest
        container_name: dotnet_app_nginx
        restart: always
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/log:/var/log/nginx
        depends_on: 
            - app-1
        ports:
            - 80:80
            - 443:443

    redis:
        image: redis
        container_name: dotnet_app_redis
        volumes:
            - "redis-dev-data:/data/storage"
            - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
        command:
            - "redis-server"
            - "/usr/local/etc/redis/"
        ports:
            - "6379:6379"

volumes: 
    redis-dev-data:    