version: "3.5"

services:
    app-1: &app
        image: vadimmakerov/valuator-app
        build:
            context: ./Valuator
        container_name: valuator-app-1
        ports:
            - 5000:5000   
        volumes:
            - ./Valuator/wwwroot:/app/wwwroot
        env_file:
            - ./Valuator/.env
        depends_on:
            - redis
            - nats
        networks:
            valuator_net:
                aliases:
                    - valuator-app-1    
            
    app-2: 
        <<: *app
        container_name: valuator-app-2
        ports:
            - 5001:5000
        networks:
            valuator_net:
                aliases:
                    - valuator-app-2

    app-3:
        <<: *app
        container_name: valuator-app-3
        ports:
            - 5002:5000
        networks:
            valuator_net:
                aliases:
                    - valuator-app-3


    events-logger-1: &events-logger
        image: vadimmakerov/events-logger
        build:
            context: ./EventsLogger
        container_name: events-logger-1
        stdin_open: true
        tty: true
        env_file:
            - ./EventsLogger/.env
        depends_on:
            - app-1
            - app-2
            - app-3
        networks:
            - valuator_net

    events-logger-2: 
        <<: *events-logger
        container_name: events-logger-2

    nginx:
        image: nginx:latest
        container_name: valuator-nginx
        networks:
            - valuator_net
        restart: always
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/log:/var/log/nginx
        depends_on: 
            - app-1
            - app-2
            - app-3
        ports:
            - 80:80
            - 443:443

    redis: &redis
        image: redis
        container_name: valuator-redis
        networks:
            - valuator_net
        volumes:
            - "redis-dev-data:/data/storage"
            - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
        command:
            - "redis-server"
            - "/usr/local/etc/redis/"
        ports:
            - "6379:6379"

    redis-ru:
        <<: *redis
        container_name: valuator-redis-ru
        volumes:
            - "redis-ru-dev-data:/data/storage"
            - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
        ports:
            - "6380:6379"

    redis-eu:
        <<: *redis
        container_name: valuator-redis-eu
        volumes:
            - "redis-eu-dev-data:/data/storage"
            - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
        ports:
            - "6381:6379"

    redis-other:
        <<: *redis
        container_name: valuator-redis-other
        volumes:
            - "redis-other-dev-data:/data/storage"
            - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
        ports:
            - "6382:6379"
    
    nats:
        image: nats
        container_name: valuator-nats
        networks:
            - valuator_net
        
networks:
    valuator_net: 
volumes: 
    redis-dev-data: 
    redis-ru-dev-data: 
    redis-eu-dev-data: 
    redis-other-dev-data: 