version: "3.3"

services:
    app:
        image: vadimmakerov/dotnet:5.0
        build:
            context: .
        container_name: dotnet_app
        working_dir: /app/Valuator
        command: dotnet run
        volumes:
            - "../:/app"
        ports:
            - 5000:5000
            - 5001:5001